apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-rollout
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        # Wir starten mit einem echten, stabilen Nginx-Image als Version 1
        image: nginx:1.25-kaputt
        ports:
        - containerPort: 80
